# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/Z008/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/Z008/proprietary/etc/firmware/BCM4335C0_003.001.009.0105.0562_Asus_ZE550ML.hcd:system/etc/firmware/BCM4335C0_003.001.009.0105.0562_Asus_ZE550ML.hcd \
    vendor/asus/Z008/proprietary/lib/hw/camera.vendor.mofd_v1.so:system/lib/hw/camera.vendor.mofd_v1.so \
    vendor/asus/Z008/proprietary/lib/hw/m10mo/camera.m10mo.so:system/lib/hw/m10mo/camera.m10mo.so \
    vendor/asus/Z008/proprietary/etc/firmware/psh.bin:system/etc/firmware/psh.bin
